# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: "license.txt|\\.md$"
      - id: mixed-line-ending
      - id: check-added-large-files
        args: ["--maxkb=30000"]
      - id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        entry: make format
