# .github/workflows/deploy.yml
name: Deploy FastAPI to Lambda

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build packaging image
        run: docker build -f Dockerfile.build -t fastapi-packager .

      - name: Extract packages
        run: |
          CID=$(docker create fastapi-packager)
          docker cp $CID:/layer.zip ./layer.zip
          docker cp $CID:/function.zip ./function.zip
          docker rm $CID
          ls -lh layer.zip function.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3) Lambda Layer 발행
      - name: Publish new layer version
        id: publish_layer
        run: |
          LAYER_ARN=$(aws lambda publish-layer-version \
            --layer-name fastapi-deps \
            --zip-file fileb://layer.zip \
            --compatible-runtimes python3.12 \
            --query 'LayerVersionArn' --output text)
          echo "layer_arn=$LAYER_ARN" >> $GITHUB_OUTPUT

      # 4) Lambda 설정 업데이트 (레이어, ENV, 타임아웃, 메모리)
      - name: Update Lambda configuration
        run: |
          aws lambda update-function-configuration \
            --function-name my-fastapi \
            --layers ${{ steps.publish_layer.outputs.layer_arn }} \
            --environment Variables="{OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }},OPENAI_BODY_ASSISTANT_ID=${{ secrets.OPENAI_BODY_ASSISTANT_ID }},OPENAI_STYLE_ASSISTANT_ID=${{ secrets.OPENAI_STYLE_ASSISTANT_ID }}}" \
            --timeout 60 \
            --memory-size 512

      # 5) Lambda 코드 배포
      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name my-fastapi \
            --zip-file fileb://function.zip

      # 6) API Gateway HTTP API 스테이지 재배포
      - name: Deploy HTTP API stage
        run: |
          API_ID=$(aws apigatewayv2 get-apis \
            --query "Items[?Name=='yourmode-api-gateway'].ApiId" --output text)
          aws apigatewayv2 create-deployment \
            --api-id "$API_ID" \
            --stage-name prod
