name: Deploy FastAPI to Lambda

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2

      - name: Build packaging image
        run: docker build -f Dockerfile.build -t fastapi-packager .

      - name: Extract function package
        run: |
          CID=$(docker create fastapi-packager)
          docker cp $CID:/package/function.zip ./function.zip
          docker rm $CID
          ls -lh function.zip

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Lambda function code
        run: |
          aws lambda update-function-code \
            --function-name my-fastapi \
            --zip-file fileb://function.zip

      - name: Update Lambda configuration
        run: |
          aws lambda update-function-configuration \
            --function-name my-fastapi \
            --environment Variables="{OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }},OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }},OPENAI_BODY_ASSISTANT_ID=${{ secrets.OPENAI_BODY_ASSISTANT_ID }},OPENAI_STYLE_ASSISTANT_ID=${{ secrets.OPENAI_STYLE_ASSISTANT_ID }}}" \
            --timeout 60 \
            --memory-size 512

      - name: Deploy API Gateway stage
        run: |
          API_ID=$(aws apigatewayv2 get-apis \
            --query "Items[?Name=='yourmode-api-gateway'].ApiId" --output text)
          aws apigatewayv2 create-deployment \
            --api-id "$API_ID" \
            --stage-name prod